const APP_VERSION='9.2.1';
const KEY='kings_cuts_v3',EXP='kings_expenses_v3',CFG='kings_cfg_v3',CLI='kings_clients_v1',REV='kings_revenues_v9';
const read=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
let cuts=read(KEY),expenses=read(EXP),clients=read(CLI),revenues=read(REV);
let cfg=Object.assign({name:'KINGS',corte:40,barba:25,combo:60,metaDia:0,metaMes:0,barbers:[]},read(CFG,{}));
const brl=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const dateKey=d=>{let x=new Date(d);return isNaN(x)?'':`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const nowLocal=()=>{let d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};
function save(){localStorage.setItem(KEY,JSON.stringify(cuts));localStorage.setItem(EXP,JSON.stringify(expenses));localStorage.setItem(CFG,JSON.stringify(cfg));localStorage.setItem(CLI,JSON.stringify(clients));localStorage.setItem(REV,JSON.stringify(revenues))}
function normalize(){expenses=expenses.map(e=>Object.assign({type:'Variável',dueDate:e.date?.slice(0,10)||dateKey(new Date()),paidDate:e.date?.slice(0,10)||null,installment:1,totalInstallments:1,recurrence:'Não recorrente',status:'paid'},e));clients=[...new Set([...clients,...cuts.map(c=>c.client).filter(Boolean)])]}
function dedupe(){
 const seen=new Set();
 const unique=(arr,keyFn)=>arr.filter(x=>{const k=keyFn(x);if(seen.has(k))return false;seen.add(k);return true});
 cuts=unique(cuts,x=>['cut',x.client||'',Number(x.price)||0,x.payment||'',x.barber||'',dateKey(x.date),new Date(x.date).getHours(),new Date(x.date).getMinutes()].join('|'));
 const clientSeen=new Set(); clients=clients.filter(n=>{let k=String(n).trim().toLocaleLowerCase();if(!k||clientSeen.has(k))return false;clientSeen.add(k);return true});
 const revSeen=new Set(); revenues=revenues.filter(x=>{let k=['rev',x.desc||'',Number(x.value)||0,x.cat||'',x.pay||'',dateKey(x.date),new Date(x.date).getHours(),new Date(x.date).getMinutes()].join('|');if(revSeen.has(k))return false;revSeen.add(k);return true});
 const expSeen=new Set(); expenses=expenses.filter(x=>{let k=['exp',x.desc||'',Number(x.value)||0,x.cat||'',x.type||'',x.dueDate||dateKey(x.date),x.installment||1,x.totalInstallments||1].join('|');if(expSeen.has(k))return false;expSeen.add(k);return true});
 save();
}
normalize();dedupe();
function periodFilter(p){let n=new Date();if(p==='day')return {from:new Date(n.getFullYear(),n.getMonth(),n.getDate()),to:new Date(n.getFullYear(),n.getMonth(),n.getDate()+1)};if(p==='week'){let f=new Date(n);f.setHours(0,0,0,0);f.setDate(n.getDate()-6);return {from:f,to:new Date()}}return {from:new Date(n.getFullYear(),n.getMonth(),1),to:new Date(n.getFullYear(),n.getMonth()+1,1)}}
function inPeriod(d,p){let x=new Date(d);return !isNaN(x)&&x>=p.from&&x<p.to}
function allIncome(){return [...cuts.map(c=>({amount:Number(c.price)||0,date:c.date,fiado:!!c.fiado,cut:c})),...revenues.map(r=>({amount:Number(r.value)||0,date:r.date,fiado:false,rev:r}))]}
function paidExpenses(){return expenses.filter(e=>e.status!=='pending')}
function totalCuts(a){return a.reduce((s,c)=>s+Number(c.price||0),0)}
function paymentLabel(p){return ({pix:'Pix',dinheiro:'Dinheiro',cartao:'Cartão',fiado:'Fiado'}[p]||'Pago')}
function cutRow(c){let d=new Date(c.date);return `<div class="row"><div><b>${esc(c.client||'Cliente avulso')}</b><small>${d.toLocaleDateString('pt-BR')} às ${d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})} · ${paymentLabel(c.payment)}${c.barber?' · '+esc(c.barber):''}</small><div class="actions">${c.fiado?`<button class="mini green" onclick="markPaid(${c.id})">Marcar pago</button>`:''}<button class="mini red" onclick="deleteCut(${c.id})">Excluir</button></div></div><div class="price">${brl(c.price)}</div></div>`}
function expenseRow(e){let due=e.dueDate||dateKey(e.date),late=e.status==='pending'&&due<dateKey(new Date());return `<div class="row"><div><b>− ${brl(e.value)}</b><small>${esc(e.desc)} · ${esc(e.cat)} · ${esc(e.type)}<br>Vence: ${new Date(due+'T12:00:00').toLocaleDateString('pt-BR')} · Parcela ${e.installment||1}/${e.totalInstallments||1}</small><div class="actions"><button class="mini ${e.status==='pending'?'green':'blue'}" onclick="toggleExpenseStatus(${e.id})">${e.status==='pending'?'Marcar paga':'Paga'}</button>${late?'<span class="mini red">VENCIDA</span>':''}<button class="mini red" onclick="deleteExpense(${e.id})">Excluir</button></div></div><div class="price">${e.status==='pending'?'A PAGAR':'SAÍDA'}</div></div>`}
function renderHome(){let d=periodFilter('day'),w=periodFilter('week'),m=periodFilter('month'),tc=cuts.filter(c=>inPeriod(c.date,d)),wc=cuts.filter(c=>inPeriod(c.date,w)),mc=cuts.filter(c=>inPeriod(c.date,m)),today=totalCuts(tc),week=totalCuts(wc),month=totalCuts(mc);todayEl.textContent=brl(today);todayCount.textContent=tc.length+' cortes registrados';weekEl.textContent=brl(week);weekCount.textContent=wc.length+' cortes';monthEl.textContent=brl(month);monthCount.textContent=mc.length+' cortes';let dp=cfg.metaDia?Math.min(100,today/cfg.metaDia*100):0,mp=cfg.metaMes?Math.min(100,month/cfg.metaMes*100):0;dayProgress.style.width=dp+'%';monthProgress.style.width=mp+'%';dayGoalText.textContent=cfg.metaDia?'Meta diária '+brl(cfg.metaDia):'Meta diária não definida';dayGoalPct.textContent=Math.round(dp)+'%';recent.innerHTML=cuts.length?cuts.slice(0,6).map(cutRow).join(''):'<div class="empty"><div class="icon">✂️</div><h3>Nenhum corte ainda</h3><p>Registre seu primeiro corte usando o +</p></div>'}
function renderCentral(){let m=periodFilter('month'),inc=allIncome().filter(x=>inPeriod(x.date,m)&&!x.fiado).reduce((s,x)=>s+x.amount,0),out=paidExpenses().filter(e=>inPeriod(e.date,m)).reduce((s,e)=>s+Number(e.value||0),0),available=allIncome().filter(x=>!x.fiado).reduce((s,x)=>s+x.amount,0)-paidExpenses().reduce((s,e)=>s+Number(e.value||0),0);v9Available.textContent=brl(available);v9Receivable.textContent=brl(cuts.filter(c=>c.fiado).reduce((s,c)=>s+Number(c.price||0),0));v9Payable.textContent=brl(expenses.filter(e=>e.status==='pending').reduce((s,e)=>s+Number(e.value||0),0));v9Profit.textContent=brl(inc-out)}
let cashPeriod='day';
function renderCash(){let p=cashPeriod==='all'?{from:new Date(0),to:new Date(8640000000000000)}:periodFilter(cashPeriod),inc=allIncome().filter(x=>inPeriod(x.date,p)),outs=expenses.filter(e=>inPeriod(e.date,p)),iv=inc.reduce((s,x)=>s+x.amount,0),ov=outs.filter(e=>e.status!=='pending').reduce((s,e)=>s+Number(e.value||0),0),pending=outs.filter(e=>e.status==='pending').reduce((s,e)=>s+Number(e.value||0),0),received=inc.filter(x=>!x.fiado).reduce((s,x)=>s+x.amount,0);cashIn.textContent=brl(iv);cashOut.textContent=brl(ov);cashSold.textContent=brl(iv);cashExpenses.textContent=brl(ov+pending);cashReceived.textContent=brl(received);cashPaid.textContent=brl(ov);cashBalance.textContent=brl(received-ov);cashBalance.className='cash-highlight-value '+(received-ov>=0?'':'neg');let all=[...cuts.map(c=>({d:c.date,h:cutRow(c)})),...revenues.map(r=>({d:r.date,h:`<div class="row"><div><b>+ ${brl(r.value)}</b><small>${esc(r.desc)} · ${esc(r.cat)}<br>${new Date(r.date).toLocaleDateString('pt-BR')}</small></div><div class="price">ENTRADA</div></div>`})),...expenses.map(e=>({d:e.date,h:expenseRow(e)}))].filter(x=>inPeriod(x.d,p)).sort((a,b)=>new Date(b.d)-new Date(a.d));cashList.innerHTML=all.length?all.slice(0,40).map(x=>x.h).join(''):'<div class="empty"><div class="icon">▤</div><h3>Caixa vazio</h3><p>Registre entradas e saídas.</p></div>'}
function renderExpenses(){let p=expensePeriod==='all'?{from:new Date(0),to:new Date(8640000000000000)}:periodFilter(expensePeriod),arr=expenses.filter(e=>inPeriod(e.date,p)).sort((a,b)=>new Date(b.dueDate||b.date)-new Date(a.dueDate||a.date));expensePageTotal.textContent=brl(arr.reduce((s,e)=>s+Number(e.value||0),0));expenseList.innerHTML=arr.map(expenseRow).join('');expenseEmpty.style.display=arr.length?'none':'block'}
function renderClients(q=''){let query=String(q).trim().toLocaleLowerCase(),shown=clients.filter(n=>!query||n.toLocaleLowerCase().includes(query));clientCount.textContent=clients.length+' clientes';clientList.innerHTML=shown.map(n=>{let cs=cuts.filter(c=>c.client===n);return `<div class="row client-row"><div class="client-main"><b>${esc(n)}</b><small>${cs.length} corte(s) · ${brl(totalCuts(cs))}</small></div></div>`}).join('');clientEmpty.style.display=shown.length?'none':'block'}
function renderRevenue(){let p=revenuePeriod==='all'?{from:new Date(0),to:new Date(8640000000000000)}:periodFilter(revenuePeriod),arr=revenues.filter(r=>inPeriod(r.date,p)).sort((a,b)=>new Date(b.date)-new Date(a.date));revenueTotal.textContent=brl(arr.reduce((s,r)=>s+Number(r.value||0),0));revenueList.innerHTML=arr.map(r=>`<div class="row"><div><b>+ ${brl(r.value)}</b><small>${esc(r.desc)} · ${esc(r.cat)} · ${esc(r.pay)}<br>${new Date(r.date).toLocaleDateString('pt-BR')}</small><div class="actions"><button class="mini red" onclick="deleteRevenue(${r.id})">Excluir</button></div></div><div class="price">ENTRADA</div></div>`).join('');revenueEmpty.style.display=arr.length?'none':'block'}
function renderReports(period='day'){let p=periodFilter(period),ins=allIncome().filter(x=>inPeriod(x.date,p)&&!x.fiado),outs=expenses.filter(e=>inPeriod(e.date,p)&&e.status!=='pending'),iv=ins.reduce((s,x)=>s+x.amount,0),ov=outs.reduce((s,e)=>s+Number(e.value||0),0);rIn.textContent=brl(iv);rOut.textContent=brl(ov);rNet.textContent=brl(iv-ov);rCuts.textContent=cuts.filter(c=>inPeriod(c.date,p)).length;let days=period==='month'?new Date().getDate():period==='week'?7:1,labels=[];for(let i=days-1;i>=0;i--){let d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);labels.push(d)}if(period==='day')labels=[new Date()];let vals=labels.map(d=>{let f=new Date(d);f.setHours(0,0,0,0);let t=new Date(f);t.setDate(t.getDate()+1);return [allIncome().filter(x=>inPeriod(x.date,{from:f,to:t})&&!x.fiado).reduce((s,x)=>s+x.amount,0),expenses.filter(e=>inPeriod(e.date,{from:f,to:t})&&e.status!=='pending').reduce((s,e)=>s+Number(e.value||0),0)]}),max=Math.max(1,...vals.flat());chart.innerHTML=labels.map((d,i)=>`<div class="bar-col"><div style="display:flex;align-items:end;gap:3px;height:150px"><div class="bar" style="height:${Math.max(3,vals[i][0]/max*140)}px"></div><div class="bar out" style="height:${Math.max(3,vals[i][1]/max*140)}px"></div></div><div class="bar-label">${d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}</div></div>`).join('')}
function renderCalendar(){let y=calCursor.getFullYear(),m=calCursor.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),start=(first.getDay()+6)%7,names=['SEG','TER','QUA','QUI','SEX','SÁB','DOM'];let h=names.map(n=>`<div class="cal-week">${n}</div>`).join('');for(let i=0;i<start;i++)h+='<div class="cal-cell muted"></div>';for(let d=1;d<=last.getDate();d++){let k=dateKey(new Date(y,m,d)),ins=allIncome().filter(x=>dateKey(x.date)===k).reduce((s,x)=>s+x.amount,0),out=expenses.filter(e=>(e.dueDate||dateKey(e.date))===k).reduce((s,e)=>s+Number(e.value||0),0),pend=expenses.some(e=>(e.dueDate||dateKey(e.date))===k&&e.status==='pending');h+=`<div class="cal-cell"><b>${d}</b>${ins?`<span class="cal-pill in">+ ${brl(ins)}</span>`:''}${out?`<span class="cal-pill out">− ${brl(out)}</span>`:''}${pend?'<span class="cal-pending">Pendente</span>':''}</div>`}calTitle.textContent=new Date(y,m,1).toLocaleDateString('pt-BR',{month:'long',year:'numeric'}).replace(/^./,c=>c.toUpperCase());calendarGrid.innerHTML=h}
let expensePeriod='all',revenuePeriod='month',calCursor=new Date(new Date().getFullYear(),new Date().getMonth(),1);
function show(id,btn){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');else{let map={home:0,cash:1,expenses:2,clients:3,more:4};if(map[id]!=null)document.querySelectorAll('.nav button')[map[id]].classList.add('active')}if(id==='calendar')renderCalendar();if(id==='settings')loadSettings();render()}
function render(){appName.textContent=cfg.name;renderHome();renderCentral();renderCash();renderExpenses();renderClients(document.querySelector('.client-search')?.value||'');renderRevenue();renderReports();renderCalendar()}
function setCashPeriod(b,p){cashPeriod=p;document.querySelectorAll('#cash .tabs button').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');renderCash()}
function setExpensePeriod(b,p){expensePeriod=p;document.querySelectorAll('#expenses .expense-filter button').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');renderExpenses()}
function setRevenuePeriod(b,p){revenuePeriod=p;document.querySelectorAll('#revenue .expense-filter button').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');renderRevenue()}
function setReportPeriod(b,p){document.querySelectorAll('#reports .tabs button').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');renderReports(p)}
function openCut(){buildServices();buildBarbers();cutTime.value=nowLocal();client.value='';document.querySelectorAll('.pay').forEach(x=>x.classList.remove('sel'));document.querySelector('.pay[data-pay="pix"]').classList.add('sel');modalCut.classList.add('open')}
function buildServices(){clientSuggestions.innerHTML=clients.map(n=>`<option value="${esc(n)}"></option>`).join('');serviceButtons.innerHTML=[['Corte',cfg.corte],['Barba',cfg.barba],['Corte + Barba',cfg.combo]].map((s,i)=>`<button class="service ${i===0?'sel':''}" onclick="chooseService(this,${s[1]})">${s[0]}<small>${brl(s[1])}</small></button>`).join('');price.value=cfg.corte}
function chooseService(el,p){document.querySelectorAll('.service').forEach(x=>x.classList.remove('sel'));el.classList.add('sel');price.value=p}
function choosePay(el,p){document.querySelectorAll('.pay').forEach(x=>x.classList.remove('sel'));el.classList.add('sel');el.dataset.pay=p}
function selectedPay(){return document.querySelector('.pay.sel')?.dataset.pay||'pix'}
function buildBarbers(){barber.innerHTML='<option value="">Selecionar barbeiro</option>'+cfg.barbers.map(b=>`<option>${esc(b)}</option>`).join('');barberList.innerHTML=cfg.barbers.length?cfg.barbers.map(b=>`<span class="chip">${esc(b)}</span>`).join(''):'<span class="chip">Nenhum cadastrado</span>'}
function saveCut(){let p=Number(price.value)||0,n=client.value.trim(),pay=selectedPay(),b=barber.value,dt=cutTime.value;if(!p)return alert('Informe o valor.');if(pay==='fiado'&&!n)return alert('Informe o cliente.');cuts.unshift({id:Date.now(),price:p,client:n,fiado:pay==='fiado',payment:pay,barber:b,date:dt?new Date(dt).toISOString():new Date().toISOString()});if(n&&!clients.includes(n))clients.unshift(n);dedupe();closeModal('modalCut');render()}
function openExpense(){v9ExpDesc.value='';v9ExpValue.value='';v9ExpDue.value=dateKey(new Date());v9ExpPaid.value='';v9ExpPart.value=1;v9ExpParts.value=1;v9ExpStatus.value='pending';modalExpense.classList.add('open')}
function saveExpenseV9(){let d=v9ExpDesc.value.trim(),v=Number(v9ExpValue.value)||0,cat=v9ExpCat.value,type=v9ExpType.value,due=v9ExpDue.value,part=Number(v9ExpPart.value)||1,total=Number(v9ExpParts.value)||1,rec=v9ExpRec.value,status=v9ExpStatus.value,paid=v9ExpPaid.value;if(!d||!v||!due)return alert('Preencha descrição, valor e vencimento.');if(part>total)return alert('Parcela inválida.');expenses.unshift({id:Date.now(),value:v,desc:d,cat,type,dueDate:due,installment:part,totalInstallments:total,recurrence:rec,status,paidDate:paid||null,date:new Date(due+'T12:00:00').toISOString()});dedupe();closeModal('modalExpense');render()}
function openRevenue(){revDesc.value='';revValue.value='';revDate.value=nowLocal();modalRevenue.classList.add('open')}
function saveRevenue(){let d=revDesc.value.trim(),v=Number(revValue.value)||0;if(!d||!v)return alert('Preencha descrição e valor.');revenues.unshift({id:Date.now(),desc:d,value:v,cat:revCat.value,pay:revPay.value,date:revDate.value?new Date(revDate.value).toISOString():new Date().toISOString()});dedupe();closeModal('modalRevenue');render()}
function closeModal(id){document.getElementById(id).classList.remove('open')}
function markPaid(id){let c=cuts.find(x=>x.id===id);if(c){c.fiado=false;c.payment='pix';c.paidAt=new Date().toISOString();save();render()}}
function toggleExpenseStatus(id){let e=expenses.find(x=>x.id===id);if(e){e.status=e.status==='pending'?'paid':'pending';e.paidDate=e.status==='paid'?dateKey(new Date()):null;save();render()}}
function deleteCut(id){if(confirm('Excluir este corte?')){cuts=cuts.filter(x=>x.id!==id);save();render()}}
function deleteExpense(id){if(confirm('Excluir esta despesa?')){expenses=expenses.filter(x=>x.id!==id);save();render()}}
function deleteRevenue(id){if(confirm('Excluir esta receita?')){revenues=revenues.filter(x=>x.id!==id);save();render()}}
function addClient(){let n=newClient.value.trim();if(!n)return;clients.push(n);dedupe();newClient.value='';renderClients()}
function addBarber(){let n=newBarber.value.trim();if(n&&!cfg.barbers.includes(n))cfg.barbers.push(n);newBarber.value='';save();buildBarbers()}
function loadSettings(){cfgName.value=cfg.name;cfgCorte.value=cfg.corte;cfgBarba.value=cfg.barba;cfgCombo.value=cfg.combo;cfgMetaDia.value=cfg.metaDia;cfgMetaMes.value=cfg.metaMes;buildBarbers()}
function saveSettings(){cfg={...cfg,name:cfgName.value.trim()||'KINGS',corte:Number(cfgCorte.value)||0,barba:Number(cfgBarba.value)||0,combo:Number(cfgCombo.value)||0,metaDia:Number(cfgMetaDia.value)||0,metaMes:Number(cfgMetaMes.value)||0};save();render();alert('Configurações salvas!')}
function clearData(){if(confirm('Apagar TODOS os dados? Esta ação não pode ser desfeita.')){cuts=[];expenses=[];clients=[];revenues=[];save();render();alert('Dados apagados.')}}
document.addEventListener('DOMContentLoaded',()=>{render();loadSettings();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=kings9.2.1',{updateViaCache:'none'}).catch(()=>{})})